### ISSUE TITLE
Feature Request: Option to Disable In-Game Music

### ISSUE THREAD

**Issue by MasterO2** [BornPosthumous/VSAV_Training#11]
@BornPosthumous 

Your VSav Training Script for FBNeo is great.

Can you also add an option to disable in-game music (unless that's turned off somewhere else)?

**Comment by NBeing** [comment]
Thanks so much for reporting an issue!
I have tried to fix this as I would really like this feature too :(
The issue with fixing this is that FBNeo has no access to the registers used by the audio.
In MAME you could also do this via cheats but FBNeo also has no cheat engine as far as I can tell.
I have requested very basic improvements to the LUA implementation (think, "save states/loading should work"), but they have fallen on deaf ears, I have also requested source code access so that I can make the necessary changes but again I think the devs are just too busy. 

J
